// Generated by CoffeeScript 1.6.2
KISSY.add(function(S, Node, Base, Checkbox) {
  var $, CheckboxUi;

  $ = Node.all;
  CheckboxUi = function(config) {
    return CheckboxUi.superclass.constructor.call(this, config);
  };
  S.extend(CheckboxUi, Base, {
    /*input元素循环后触发
    */

    _inputEachHandler: function(ev) {
      var $input;

      $input = ev.$el;
      if (!this._isRenderUi($input)) {
        return true;
      }
      this.set('target', $input);
      return this._renderUi(Checkbox);
    }
  }, {
    ATTRS: {
      type: {
        value: 'checkbox'
      },
      defaultConfig: {
        value: {
          cssUrl: ''
        }
      }
    }
  });
  return CheckboxUi;
}, {
  requires: ['node', './radio', 'gallery/checkbox/1.4/']
});
