// Generated by CoffeeScript 1.6.2
(function() {
  KISSY.add(function(S, Node, Base, TextMagnifier) {
    var $, TextMagnifierUi;

    $ = Node.all;
    TextMagnifierUi = function(config) {
      return TextMagnifierUi.superclass.constructor.call(this, config);
    };
    S.extend(TextMagnifierUi, Base, {
      /*input元素循环后触发
      */

      _inputEachHandler: function(ev) {
        var $input, config, id;

        $input = ev.$el;
        if (!this._isRenderUi($input)) {
          return true;
        }
        this.set('target', $input);
        id = $input.attr('id');
        if (!id) {
          id = 'bf-' + S.guid();
          $input.attr('id', id);
        }
        config = this.get('config');
        S.mix(config, {
          id: '#' + id
        });
        this.set('config', config);
        return this._renderUi(TextMagnifier, config);
      },
      _renderUi: function(UiClass, config) {
        var cls;

        cls = new UiClass(config);
        cls.render();
        this.set('ui', cls);
        return cls;
      }
    }, {
      ATTRS: {
        type: {
          value: 'magnifier'
        },
        /*目标元素
        */

        target: {
          value: ''
        },
        defaultConfig: {
          value: {
            align: "top",
            delimiter: ''
          }
        }
      }
    });
    return TextMagnifierUi;
  }, {
    requires: ['node', './base', 'gallery/textMagnifier/1.0/']
  });

}).call(this);
