// Generated by CoffeeScript 1.6.2
KISSY.add(function(S, Node, Base, Spinbox) {
  var $, Number;

  $ = Node.all;
  Number = function(config) {
    return Number.superclass.constructor.call(this, config);
  };
  S.extend(Number, Base, {
    /*input元素循环后触发
    */

    _inputEachHandler: function(ev) {
      var $input;

      $input = ev.$el;
      if (!this._isRenderUi($input)) {
        return true;
      }
      this.set('target', $input);
      return this._renderUi(Spinbox);
    }
  }, {
    ATTRS: {
      type: {
        value: 'spinbox'
      },
      /*目标元素
      */

      target: {
        value: ''
      },
      defaultConfig: {
        value: {
          cssUrl: ''
        }
      }
    }
  });
  return Number;
}, {
  requires: ['node', './base', 'gallery/spinbox/1.4/']
});
