// Generated by CoffeeScript 1.6.2
KISSY.add(function(S, Node, RichBase) {
  var $, Butterfly;

  $ = Node.all;
  return Butterfly = RichBase.extend({
    constructor: function(target, config) {
      var self;

      if (config == null) {
        config = {};
      }
      self = this;
      Butterfly.superclass.constructor.call(self, config);
      return self.set('target', target);
    },
    /*
    运行组件
    */

    render: function() {
      return this._eachEl();
    },
    field: function() {},
    /*遍历表单元素
    */

    _eachEl: function() {
      var $inputs, $selects, $target, $textareas, self;

      self = this;
      $target = self.get('target');
      if (!$target.length) {
        return false;
      }
      $inputs = $target.all('input');
      $inputs.each(function($el) {
        return self.fire('inputEach', {
          $el: $el
        });
      });
      $selects = $target.all('select');
      $selects.each(function($el) {
        $el.attr('type', 'select');
        return self.fire('selectEach', {
          $el: $el
        });
      });
      $textareas = $target.all('textarea');
      return $textareas.each(function($el) {
        if (!$el.attr('type')) {
          $el.attr('type', 'textarea');
        }
        return self.fire('textareaEach', {
          $el: $el
        });
      });
    }
  }, {
    ATTRS: {
      /*目标元素
      */

      target: {
        value: '',
        getter: function(v) {
          return $(v);
        }
      },
      /*Ui实例集合
      */

      uis: {
        value: {}
      }
    }
  });
}, {
  requires: ['node', 'rich-base']
});
